### ISSUE TITLE
t\links.t on systems that support symlink but when current user is not allowed (Windows case)

### ISSUE THREAD

**Issue by jddurand** [briandfoy/test-file#36] opened 2022-10-06 19:30 UTC
Using a perl-5.36.0 built myself using cl of Visual Studio 2022 Community Edition, on a Windows 10 box, version 21H1.

I wonder if using the test at https://perldoc.perl.org/functions/symlink is enough. Indeed, on recent versions of Windows 10, this is supported, though not guaranteed to work. My test case is a Windows box symlink seems to be supported:

```
C:\Users\jddfr\git\perlbuildwindows-build>"C:\perl\5.36.0\bin\MSWin32-x86-multi-thread\perl.exe" -e "symlink('','')"

C:\Users\jddfr\git\perlbuildwindows-build>echo %ERRORLEVEL%
0
```

but where I am not allowed to do so:

```
C:\Users\jddfr\git\perlbuildwindows-build>if exist testFile del /Q /F testFile

C:\Users\jddfr\git\perlbuildwindows-build>if exist testFile2 del /Q /F testFile2

C:\Users\jddfr\git\perlbuildwindows-build>echo TEST > testFile

C:\Users\jddfr\git\perlbuildwindows-build>"C:\perl\5.36.0\bin\MSWin32-x86-multi-thread\perl.exe" -e "symlink(shift,shift) || print $!" "testFile" "testFile2"
Operation not permitted
```

As a consequence `t\links.t` is likely to fail, at least this is what I observe. 

Please note that the suggestion from [perlport#symlink](https://perldoc.perl.org/perlport#symlink) seems worth to look at:

```
C:\Users\jddfr\git\perlbuildwindows-build>"C:\perl\5.36.0\bin\MSWin32-x86-multi-thread\perl.exe" -MWin32 -e "print Win32::IsSymlinkCreationAllowed() ? 'ok' : 'ko'"
ko
```

All in all here is the full test using cpanm:

```
Building and testing Test-File-1.992

Microsoft (R) Program Maintenance Utility Version 14.32.31332.0
Copyright (C) Microsoft Corporation. Tous droits réservés.

cp lib/Test/File.pm blib\lib\Test\File.pm

Microsoft (R) Program Maintenance Utility Version 14.32.31332.0
Copyright (C) Microsoft Corporation. Tous droits réservés.

	"C:\perl\5.36.0\bin\MSWin32-x86-multi-thread\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t\*.t t\*\*.t
    # MSWin32
t\dm_skeleton.t ............... ok
t\file_contains.t ............. ok
t\file_contains_encoded.t ..... ok
t\file_contains_utf8.t ........ ok
t\file_mtime.t ................ ok
t\file_sizes.t ................ ok
t\line_counters.t ............. ok
t\link_counts.t ............... ok
    # file [readable_sym] does not exist

    #   Failed test 'readable_sym exists'
    #   at t\links.t line 64.
    # file [dangle_sym] does not exist

    #   Failed test 'dangle_sym exists'
    #   at t\links.t line 65.
    # file [dangle_sym] is not a symlink

    #   Failed test 'dangle_sym is a symlink'
    #   at t\links.t line 66.
    # file [dangle_sym] is not a symlink

    #   Failed test 'dangle_sym is a symlink'
    #   at t\links.t line 70.

    #   Failed test at t\links.t line 78.
    # STDOUT is:
    # >     not ok 1 - readable_sym is a symlink
    # not:
    # >     ok 1 - readable_sym is a symlink
    # as expected
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'readable_sym is a symlink'
    # >     #   at t\links.t line 77.
    # not:
    # > 
    # > 
    # > 
    # as expected

    #   Failed test at t\links.t line 82.
    # STDOUT is:
    # >     not ok 1 - This is my test name
    # not:
    # >     ok 1 - This is my test name
    # as expected
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'This is my test name'
    # >     #   at t\links.t line 81.
    # not:
    # > 
    # > 
    # > 
    # as expected

    #   Failed test at t\links.t line 86.
    # STDOUT is:
    # >     not ok 1 - This is my test name
    # not:
    # >     ok 1 - This is my test name
    # as expected
    # STDERR is:
    # >     # file [dangle_sym] is not a symlink
    # >     #   Failed test 'This is my test name'
    # >     #   at t\links.t line 85.
    # not:
    # > 
    # > 
    # > 
    # as expected

    #   Failed test at t\links.t line 90.
    # STDOUT is:
    # >     not ok 1 - This is my test name
    # not:
    # >     ok 1 - This is my test name
    # as expected
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'This is my test name'
    # >     #   at t\links.t line 89.
    # not:
    # > 
    # > 
    # > 
    # as expected

    #   Failed test at t\links.t line 95.
    # STDOUT is:
    # >     not ok 1 - readable_sym is a symlink
    # >     not ok 2 - This is my test name
    # not:
    # >     ok 1 - readable_sym is a symlink
    # >     ok 2 - This is my test name
    # as expected
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'readable_sym is a symlink'
    # >     #   at t\links.t line 93.
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'This is my test name'
    # >     #   at t\links.t line 94.
    # not:
    # > 
    # > 
    # > 
    # > 
    # > 
    # > 
    # as expected
    # Looks like you failed 3 tests of 13.

#   Failed test 'should_work'
#   at t\links.t line 97.

    #   Failed test at t\links.t line 158.
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    #       #   Failed test 'readable_sym is a symlink'
    #       #   at t\links.t line 157.
    # not:
    # >     # symlink [readable_sym] points to non-existent target [not_there]
    #       #   Failed test 'readable_sym is a symlink'
    #       #   at t\links.t line 157.
    # as expected

    #   Failed test at t\links.t line 168.
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'symlink readable_sym points to not_there'
    # >     #   at t\links.t line 167.
    # > 
    # not:
    # >     #   Failed test 'symlink readable_sym points to not_there'
    # >     #   at t\links.t line 167.
    # >     #        got: readable
    # >     #   expected: not_there
    # as expected
    # Looks like you failed 2 tests of 2.

#   Failed test 'bad_target_does_not_exist'
#   at t\links.t line 170.

    #   Failed test at t\links.t line 182.
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    # >     #   Failed test 'readable_sym is a symlink'
    # >     #   at t\links.t line 181.
    # > 
    # > 
    # not:
    # >     # symlink [readable_sym] points to
    # >     #          got: readable
    # >     #     expected: writable
    # >     #   Failed test 'readable_sym is a symlink'
    # >     #   at t\links.t line 181.
    # as expected
    # Looks like you failed 1 test of 1.

#   Failed test 'bad_target_does_exists'
#   at t\links.t line 184.

    #   Failed test at t\links.t line 201.
    # STDERR is:
    # >     # file [readable_sym] is not a symlink
    #       #   Failed test 'This is my test name'
    #       #   at t\links.t line 199.
    # >     # file [readable_sym] is not a symlink
    #       #   Failed test 'readable_sym is a symlink'
    #       #   at t\links.t line 200.
    # not:
    # >     # symlink [readable_sym] points to existing file [readable] but shouldn't
    #       #   Failed test 'This is my test name'
    #       #   at t\links.t line 199.
    # >     # symlink [readable_sym] points to existing file [readable] but shouldn't
    #       #   Failed test 'readable_sym is a symlink'
    #       #   at t\links.t line 200.
    # as expected
    # Looks like you failed 1 test of 1.

#   Failed test 'dangling_exists'
#   at t\links.t line 203.
# Looks like you failed 4 tests of 11.
t\links.t ..................... 
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/11 subtests 
t\load.t ...................... ok
t\normalize.t ................. ok
t\obviously_non_multi_user.t .. ok
t\owner.t ..................... skipped: I can't find a file to test with: The getpwuid function is unimplemented at t\owner.t line 22.
t\pod.t ....................... ok
t\pod_coverage.t .............. skipped: Test::Pod::Coverage 1.00 required for testing POD coverage
    # File is min_file with size 53 bytes
t\rt\30346.t .................. ok
t\test_dirs.t ................. ok
# Warnings about file_writeable_ok are fine. It's a deprecated name that still works.
t\test_files.t ................ ok
t\win32.t ..................... ok

Test Summary Report
-------------------
t\links.t                   (Wstat: 1024 (exited 4) Tests: 11 Failed: 4)
  Failed tests:  7, 9-11
  Non-zero exit status: 4
Files=19, Tests=181,  4 wallclock secs ( 0.06 usr +  0.02 sys =  0.08 CPU)
Result: FAIL
Failed 1/19 test programs. 4/181 subtests failed.
NMAKE : fatal error U1077: 'C:\perl\5.36.0\bin\MSWin32-x86-multi-thread\perl.exe' : code retour '0xff'
Stop.

```

**Comment by briandfoy** [comment] 2022-10-07 10:18
Try the code I have in the `briandfoy/GH36-windows-symlinks` branch. If that doesn't work, perhaps you can adjust it to get what you think it should be.

**Comment by jddurand** [comment] 2022-10-07 15:45
Many thanks for the change in `lib\Test\File.pm` that seems ok. Nevertheless the test suite should use it IMHO, c.f. pull request https://github.com/briandfoy/test-file/pull/38 .

**Comment by briandfoy** [comment] 2022-10-07 17:15
Right now I'm stuck on the first bullet, since Strawberry Perl v5.32 (the latest version) has Win32 0.54. That does not have Win32::IsSymlinkCreationAllowed. 

I'm tempted to lift the sub right out of Win32.pm. I don't have time for this tonight, but if you want to try it to see if it works on the older Perls, go for it.

```
sub IsSymlinkCreationAllowed {
    my(undef, $major, $minor, $build) = GetOSVersion();

    # Vista was the first Windows version with symlink support
    return !!0 if $major < 6;

    # Since Windows 10 1703, enabling the developer mode allows to create
    # symlinks regardless of process privileges
    if ($major > 10 || ($major == 10 && ($minor > 0 || $build > 15063))) {
        return !!1 if IsDeveloperModeEnabled();
    }

    my $privs = GetProcessPrivileges();

    return !!0 unless $privs;

    # It doesn't matter if the permission is enabled or not, it just has to
    # exist. CreateSymbolicLink() will automatically enable it when needed.
    return exists $privs->{SeCreateSymbolicLinkPrivilege};
}
```

**Comment by jddurand** [comment] 2022-10-12 18:29
For externals reading this issue, there is pull request https://github.com/briandfoy/test-file/pull/40 that _should_ be ok on all Windows.

**Comment by jddurand** [comment] 2022-10-16 01:40
Note that I start to wonder if another way, on Win32 only, would be to use an eval-protected version of  perl's officiel test suite at https://github.com/Perl/perl5/blob/blead/t/win32/symlink.t , i.e. 

```
Win32::FsType() eq 'NTFS'
    or skip_all("need NTFS");

plan skip_all => "no symlink available in this Windows"
    if !symlink('', '') && $! == &Errno::ENOSYS;

my $tmpfile1 = tempfile();
my $tmpfile2 = tempfile();

my $ok = symlink($tmpfile1, $tmpfile2);
plan skip_all => "no access to symlink as this user"
     if !$ok && $! == &Errno::EPERM;
```

**Comment by jddurand** [comment] 2022-10-16 01:40
Note that I start to wonder if another way, on Win32 only, would be to use an eval-protected version of  perl's officiel test suite at https://github.com/Perl/perl5/blob/blead/t/win32/symlink.t , i.e. 

```
Win32::FsType() eq 'NTFS'
    or skip_all("need NTFS");

plan skip_all => "no symlink available in this Windows"
    if !symlink('', '') && $! == &Errno::ENOSYS;

my $tmpfile1 = tempfile();
my $tmpfile2 = tempfile();

my $ok = symlink($tmpfile1, $tmpfile2);
plan skip_all => "no access to symlink as this user"
     if !$ok && $! == &Errno::EPERM;
```

**Comment by jddurand** [comment] 2022-10-17 03:09
FYI I pushed a diff against Test-File-1.992 at https://github.com/jddurand/perlbuildwindows/blob/main/patches/Test-File-1.992-windows-symlinks.patch .

**Comment by briandfoy** [comment] 2022-11-09 23:09
I've merged this and a few other things and am working through the test failures (see the Actions results). Some of that is probably unrelated to this issue.

**Comment by briandfoy** [comment] 2022-11-10 22:01
Okay, I've worked out a few minor regressions unrelated to this issue and released 1.992_01 so CPAN Testers can try it.

**Comment by jddurand** [comment] 2022-12-31 13:25
The version 1.992_01 has a single failure up to now c.f. http://www.cpantesters.org/cpan/report/59a596d5-703f-1014-8ade-9418032c038b because it runs on a very old Windows version IMHO. Do you think this can be ignored ?

**Comment by jddurand** [comment] 2022-12-31 13:26
NB: Note that putting 1.992_01 in dependencies in Makefile.PL seems to have no effect, for me at least. I have to say `cpan BDFOY/Test-File-1.992_01.tar.gz` to get it installed.

**Comment by briandfoy** [comment] 2022-12-31 20:36
Yes, I'll ignore v5.8 on Windows 7. :) I've released 1.993 to CPAN.

**Closed by briandfoy** 2022-12-31 20:36 UTC
Labels: Win32, Testing

**Comment by jddurand** [comment] 2023-01-01 13:10
@briandfoy many thanks. I tried this morning, and do not see 1.993 version even with a cpan reload index (?)

**Comment by jddurand** [comment] 2023-01-02 04:06
> @briandfoy many thanks. I tried this morning, and do not see 1.993 version even with a cpan reload index (?)

Please ignore - got it from CPAN. Thanks.
